name: GCP Cloud Run CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up GCP authentication
    - id: 'auth'
      name: Set up Google Cloud credentials
      uses: google-github-actions/auth@v2.0.0
      with:
        workload_identity_provider: 'projects/757651747361/locations/global/workloadIdentityPools/workload-identity/providers/workload-identity-provider'
        service_account: 'collect-data@data-platform-436510.iam.gserviceaccount.com'

    # Configure Docker for Google Cloud
    - name: Configure Docker to use GCR
      run: |
        gcloud --quiet auth configure-docker ${{ secrets.GOOGLE_CONTAINER_REGISTRY_REGION }}-docker.pkg.dev

    # Build the Docker image
    - name: Build the Docker image
      run: |
        IMAGE_NAME=${{ secrets.GOOGLE_CONTAINER_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/data-platform-images/${{ secrets.CLOUD_RUN_SERVICE }}:$(echo $GITHUB_SHA | cut -c1-8)
        docker build -t $IMAGE_NAME -f ./collect-data/Dockerfile ./collect-data

    # Push the Docker image to GCR
    - name: Push Docker image to Google Container Registry
      run: |
        IMAGE_NAME=${{ secrets.GOOGLE_CONTAINER_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/data-platform-images/${{ secrets.CLOUD_RUN_SERVICE }}:$(echo $GITHUB_SHA | cut -c1-8)
        docker push $IMAGE_NAME

    # Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        IMAGE_NAME=${{ secrets.GOOGLE_CONTAINER_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/data-platform-images/${{ secrets.CLOUD_RUN_SERVICE }}:$(echo $GITHUB_SHA | cut -c1-8)
        gcloud run jobs update ${{ secrets.CLOUD_RUN_SERVICE }} \
          --image=$IMAGE_NAME \
          --region=${{ secrets.GOOGLE_CONTAINER_REGISTRY_REGION }} \
          --project=${{ secrets.GCP_PROJECT }} \
          --max-retries=3 \
          --memory=512Mi \
          --task-timeout=900s \
          --command="python app/generic-collect-api-data.py"

    # Set up Cloud Scheduler
    - name: Set up Cloud Scheduler Job
      run: |
        gcloud scheduler jobs create http api-to-gcs-job \
          --schedule "0 8 * * *" \  # Update this to your preferred schedule (e.g., every hour)
          --uri "https://${{ secrets.GCR_REGION }}-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/${{ secrets.GCP_PROJECT }}/jobs/${{ secrets.CLOUD_RUN_SERVICE }}:run" \
          --http-method POST \
          --oauth-service-account-email collect-data@data-platform-436510.iam.gserviceaccount.com \
          --time-zone "UTC" \
          --description "Periodic trigger for Cloud Run"

